export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const BASE_PATH = 'api/v1';
export const DEFAULT_LANG = 'en';
export const DEFAULT_PASSWORD = 'Abc13579';
export const ErrorCodes = {
  ERROR_CODE_SUCCESS: 200,
  ERROR_CODE_UNAUTHORIZED: 401,
  ERROR_CODE_INVALID_USERNAME_OR_PASSWORD: 303,
  ERROR_CODE_FORBIDDEN: 403,
  ERROR_CODE_API_BAD_REQUEST: 400,
  ERROR_CODE_API_NOT_FOUND: 404,
  ERROR_CODE_OLD_PASSWORD_NOT_CORRECT: 405,
  ERROR_CODE_EMAIL_EXIST: 406,
  ERROR_CODE_EMAIL_DONT_EXIST: 417,
  ERROR_CODE_ITEM_EXIST: 407,
  ERROR_CODE_ITEM_NOT_EXIST: 408,
  ERROR_CODE_UPLOAD_ERROR: 409,
  ERROR_CODE_IMPORT_CSV_FAIL: 410,
  ERROR_CODE_ITEM_IN_USE: 411,
  ERROR_CODE_WORK_ORDER_IS_ACTIVE: 412,
  ERROR_CODE_PROJECT_IS_ACTIVE: 413,
  ERROR_CODE_CHANGE_STATUS_NOT_SUCCESS: 414,
  ERROR_CODE_LOCKED_ACCOUNT_TEMPORARILY: 415,
  ERROR_CODE_LOCKED_ACCOUNT_PERMANENTLY: 416,
  ERROR_CODE_INVALID_PARAMETER: 422,
  ERROR_CODE_SYSTEM_ERROR: 500,
  ERROR_CODE_USER_EXIST:501,
  ERROR_CODE_SERVER_TEMPORARILY_UNAVAILABLE: 503,

  ERROR_CODE_OTP_NOT_EXIST: 40001,

  ERROR_CODE_USER_NOT_EXIST: 40100,
  ERROR_CODE_WRONG_OLD_PASSWORD: 40101,
};

export const ErrorCodeMessages = {
  ERROR_CODE_SUCCESS: { code: 200, message: 'success' },
  ERROR_CODE_UNAUTHORIZED: { code: 401, message: 'unauthorized' },

  ERROR_CODE_OTP_NOT_EXIST: { code: 40001, message: 'Otp not existed' },
  ERROR_CODE_USER_NOT_EXIST: { code: 40100, message: 'User not existed' },
  ERROR_CODE_WRONG_OLD_PASSWORD: { code: 40101, message: 'Old password wrong' },
};
